[package]
# be a sign or warning of (an imminent event, typically an unwelcome one).
name = "presage"
version = "0.1.0"
authors = ["Gabriel Féron <feron.gabriel@gmail.com>"]
edition = "2018"

[dependencies]
libsignal-service = { git = "https://github.com/Michael-F-Bryan/libsignal-service-rs" }
libsignal-service-hyper = { git = "https://github.com/Michael-F-Bryan/libsignal-service-rs.git" }
env_logger = "0.7"
directories = "3.0"
structopt = "0.3"
image = { version = "0.23", default-features = false, features = ["png"] }
qrcode = "0.12"
opener = "0.4"
rand = "0.7"
anyhow = "1.0"
thiserror = "1.0"
base64 = "0.12"
serde_json = "1.0"
futures = "0.3"
serde = "1.0"
log = "0.4.8"
sled = "*"
prost = "*"
hex = "0.4.2"
tokio = { version = "1.0", features = [ "macros", "rt-multi-thread" ] }
async-trait = "0.1"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_async = "*"

#[patch."https://github.com/Michael-F-Bryan/libsignal-service-rs.git"]
#libsignal-service = { path = "../libsignal-service-rs/libsignal-service" }
#libsignal-service-hyper = { path = "../libsignal-service-rs/libsignal-service-hyper" }

[features]
quirks = []
