[package]
# be a sign or warning of (an imminent event, typically an unwelcome one).
name = "presage"
version = "0.1.0"
authors = ["Gabriel Féron <feron.gabriel@gmail.com>"]
edition = "2018"

[dependencies]
libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs" }
libsignal-service-hyper = { git = "https://github.com/whisperfish/libsignal-service-rs.git" }

anyhow = "1.0"
async-trait = "0.1"
base64 = "0.12"
directories = "3.0"
env_logger = "0.7"
futures = "0.3"
hex = "0.4.2"
image = { version = "0.23", default-features = false, features = ["png"] }
log = "0.4.8"
opener = "0.4"
qrcode = "0.12"
rand = "0.7"
serde = "1.0"
serde_json = "1.0"
sled = "0.34"
structopt = "0.3"
thiserror = "1.0"
tokio = { version = "1.0", features = [ "macros", "rt-multi-thread" ] }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_async = "0.1"

#[patch."https://github.com/gferon/libsignal-service-rs.git"]
#libsignal-service = { path = "../libsignal-service-rs/libsignal-service" }
#libsignal-service-hyper = { path = "../libsignal-service-rs/libsignal-service-hyper" }

[features]
quirks = []
